import { CellTowerNode, Incident, TimeSeriesPoint, AIAnalysisResult } from '../src/types';

export const INITIAL_TOWERS: CellTowerNode[] = [
  {
    id: 'TWR-US-E1-04',
    name: 'US-East-1 Edge Tower 04 (NoVA)',
    region: 'us-east-1',
    coordinates: [24, 38], // % across 100x100 relative world map
    city: 'Ashburn, VA',
    country: 'United States',
    type: '5G-gNodeB',
    status: 'CRITICAL',
    latency: 82.0,
    packetLoss: 8.7,
    throughput: 41.2,
    jitter: 28.4,
    activeUsers: 2490,
    rsrp: -104,
    sinr: 6.4,
    ipAddress: '198.51.100.24',
    lastUpdated: 'Just now',
  },
  {
    id: 'TWR-US-W2-02',
    name: 'US-West-2 Edge Gateway (Oregon)',
    region: 'us-west-2',
    coordinates: [15, 33],
    city: 'Boardman, OR',
    country: 'United States',
    type: '5G-gNodeB',
    status: 'NORMAL',
    latency: 22.4,
    packetLoss: 0.12,
    throughput: 460.0,
    jitter: 3.2,
    activeUsers: 1420,
    rsrp: -81,
    sinr: 18.2,
    ipAddress: '198.51.100.89',
    lastUpdated: 'Just now',
  },
  {
    id: 'TWR-EU-C1-01',
    name: 'EU-Central-1 gNodeB (Frankfurt)',
    region: 'eu-central-1',
    coordinates: [52, 28],
    city: 'Frankfurt',
    country: 'Germany',
    type: '5G-gNodeB',
    status: 'NORMAL',
    latency: 18.5,
    packetLoss: 0.08,
    throughput: 520.4,
    jitter: 2.5,
    activeUsers: 1980,
    rsrp: -78,
    sinr: 22.0,
    ipAddress: '203.0.113.14',
    lastUpdated: 'Just now',
  },
  {
    id: 'TWR-EU-W2-03',
    name: 'London Metro Core Hub (Canary Wharf)',
    region: 'eu-west-2',
    coordinates: [48, 26],
    city: 'London',
    country: 'United Kingdom',
    type: 'Edge-MEC',
    status: 'WARNING',
    latency: 58.2,
    packetLoss: 3.8,
    throughput: 185.0,
    jitter: 14.6,
    activeUsers: 3120,
    rsrp: -92,
    sinr: 11.4,
    ipAddress: '203.0.113.88',
    lastUpdated: 'Just now',
  },
  {
    id: 'TWR-AP-NE1-05',
    name: 'Tokyo Bay mmWave Array (Shibuya)',
    region: 'ap-northeast-1',
    coordinates: [85, 39],
    city: 'Tokyo',
    country: 'Japan',
    type: '5G-gNodeB',
    status: 'NORMAL',
    latency: 14.2,
    packetLoss: 0.05,
    throughput: 840.0,
    jitter: 1.8,
    activeUsers: 4210,
    rsrp: -74,
    sinr: 25.8,
    ipAddress: '192.0.2.112',
    lastUpdated: 'Just now',
  },
  {
    id: 'TWR-AP-SE1-06',
    name: 'Singapore Changi Hub eNodeB',
    region: 'ap-southeast-1',
    coordinates: [78, 56],
    city: 'Singapore',
    country: 'Singapore',
    type: '4G-eNodeB',
    status: 'NORMAL',
    latency: 28.6,
    packetLoss: 0.42,
    throughput: 142.5,
    jitter: 5.4,
    activeUsers: 1890,
    rsrp: -86,
    sinr: 15.2,
    ipAddress: '192.0.2.240',
    lastUpdated: 'Just now',
  },
  {
    id: 'TWR-SA-E1-07',
    name: 'São Paulo South Carrier Exchange',
    region: 'sa-east-1',
    coordinates: [34, 72],
    city: 'São Paulo',
    country: 'Brazil',
    type: '4G-eNodeB',
    status: 'WARNING',
    latency: 64.0,
    packetLoss: 2.9,
    throughput: 95.0,
    jitter: 16.8,
    activeUsers: 1650,
    rsrp: -95,
    sinr: 9.8,
    ipAddress: '198.18.0.44',
    lastUpdated: 'Just now',
  },
];

export const INITIAL_TIME_SERIES: TimeSeriesPoint[] = [
  { time: '12:00', latency: 28, packetLoss: 0.8, throughput: 110, jitter: 6.2 },
  { time: '12:15', latency: 31, packetLoss: 0.9, throughput: 105, jitter: 6.8 },
  { time: '12:30', latency: 36, packetLoss: 1.2, throughput: 98, jitter: 8.1 },
  { time: '12:45', latency: 42, packetLoss: 1.6, throughput: 92, jitter: 9.4 },
  { time: '13:00', latency: 49, packetLoss: 2.4, throughput: 84, jitter: 12.0 },
  { time: '13:15', latency: 58, packetLoss: 3.8, throughput: 72, jitter: 16.5 },
  { time: '13:30', latency: 65, packetLoss: 4.9, throughput: 61, jitter: 19.8 },
  { time: '13:45', latency: 74, packetLoss: 6.7, throughput: 52, jitter: 24.1 },
  { time: '14:00', latency: 80, packetLoss: 8.1, throughput: 44, jitter: 27.5, anomaly: true, anomalyNote: 'Congestion Threshold Crossed' },
  { time: '14:15', latency: 85, packetLoss: 9.2, throughput: 38, jitter: 31.0, anomaly: true, anomalyNote: 'Packet Loss Anomaly' },
  { time: '14:30', latency: 82, packetLoss: 8.7, throughput: 41, jitter: 28.4, anomaly: true, anomalyNote: 'Current Snapshot' },
];

export const INITIAL_AI_ANALYSIS: AIAnalysisResult = {
  incidentTitle: 'Packet Loss Anomaly Detected!',
  severity: 'CRITICAL',
  probableCause: 'Network congestion or packet-delivery issues correlated with high TCP retransmissions.',
  confidenceScore: 94.6,
  technicalDetails: 'Interface eth0/ge-0/0/3 on US-East-1 Edge Tower 04 experiencing 14.8% CRC frame discards and buffer overrun. Upstream transit peering at Ashburn Equinix IX showed 92% link utilization during 14:00-14:30 UTC peak window.',
  correlatedMetrics: ['TCP Retransmissions (+340%)', 'Optical SFP Receive Power Drop (-3.2dBm)', 'Buffer Queue Depletion'],
  impactAssessment: 'Impacting ~2,490 active connected 5G subscribers and streaming video sessions in North Virginia region.',
  affectedNodes: ['TWR-US-E1-04 (Ashburn, VA)', 'Edge-MEC Ashburn Pod-2'],
  recommendedActions: [
    {
      id: 'act-reroute',
      title: 'Inspect affected interfaces & reroute core traffic',
      description: 'Divert egress flow to secondary 100G dark fiber path via US-East-1b interconnect.',
      riskLevel: 'LOW',
      actionType: 'reroute',
      estimatedRecoverySec: 25,
    },
    {
      id: 'act-beamform',
      title: 'Check interface errors & utilization',
      description: 'Trigger autonomous interface queue flush and re-tune 5G beamforming tilt angle.',
      riskLevel: 'LOW',
      actionType: 'beamform',
      estimatedRecoverySec: 40,
    },
    {
      id: 'act-rate-limit',
      title: 'Verify routing paths & apply QoS shaping',
      description: 'Prioritize ultra-reliable low latency (URLLC) traffic and rate-limit bulk background syncs.',
      riskLevel: 'MEDIUM',
      actionType: 'optimize_qos',
      estimatedRecoverySec: 15,
    },
    {
      id: 'act-analyze-tcp',
      title: 'Analyze TCP retransmissions & restart MEC session',
      description: 'Recycle TCP socket pool on Edge-MEC pod to purge poisoned congestion windows.',
      riskLevel: 'LOW',
      actionType: 'restart_mec',
      estimatedRecoverySec: 30,
    },
  ],
  telemetrySnapshot: {
    latency: 82.0,
    packetLoss: 8.7,
    throughput: 41.2,
    jitter: 28.4,
    rsrp: -104,
  },
  generatedAt: '2026-10-02T14:30:15Z',
  sourceModel: 'Gemini 3.8 Flash Operations Copilot',
};

export const INITIAL_INCIDENTS: Incident[] = [
  {
    id: 'INC-2026-9041',
    title: 'Severe Packet Loss & High Latency on NoVA 5G Cell',
    timestamp: '10 mins ago',
    severity: 'CRITICAL',
    status: 'Active',
    region: 'us-east-1',
    towerId: 'TWR-US-E1-04',
    towerName: 'US-East-1 Edge Tower 04 (NoVA)',
    metric: 'Packet Loss (8.7%) & Latency (82ms)',
    currentValue: '8.7% Loss / 82ms',
    baselineValue: '0.15% Loss / 24ms',
    rootCause: 'Optical transponder degrade and egress queue saturation on upstream spine router switch.',
    impact: 'Elevated buffering for 2,490 active users; URLLC degraded.',
    recommendedActions: [
      'Reroute traffic to secondary 100G transit',
      'Flush TCP congestion window',
      'Dispatch field technician to inspect Ashburn fiber patch',
    ],
    remediationExecuted: false,
    remediationLog: [],
  },
  {
    id: 'INC-2026-8892',
    title: 'Intermittent Carrier Aggregation Jitter Surge',
    timestamp: '2 hours ago',
    severity: 'WARNING',
    status: 'Investigating',
    region: 'eu-west-2',
    towerId: 'TWR-EU-W2-03',
    towerName: 'London Metro Core Hub (Canary Wharf)',
    metric: 'Jitter (14.6ms)',
    currentValue: '14.6 ms',
    baselineValue: '3.1 ms',
    rootCause: 'Microwave backhaul fade caused by heavy storm cell in Thames Estuary.',
    impact: 'Minor jitter on real-time VoNR calls.',
    recommendedActions: [
      'Switch modulation scheme from 256-QAM to 64-QAM',
      'Enable adaptive beamsteering',
    ],
    remediationExecuted: false,
  },
  {
    id: 'INC-2026-8710',
    title: 'Mid-band 5G Radio Interlock Handover Drop',
    timestamp: '5 hours ago',
    severity: 'WARNING',
    status: 'Mitigated',
    region: 'sa-east-1',
    towerId: 'TWR-SA-E1-07',
    towerName: 'São Paulo South Carrier Exchange',
    metric: 'Handover Failure Rate (4.1%)',
    currentValue: '4.1%',
    baselineValue: '0.2%',
    rootCause: 'Neighbor cell relation (ANR) misconfiguration after firmware rollout.',
    impact: 'Brief call drops when roaming between sector 2 and 3.',
    recommendedActions: [
      'Rolled back ANR neighbor table to revision v4.18',
      'Recalibrated intra-frequency handover margins',
    ],
    remediationExecuted: true,
    remediationLog: [
      '10:14:02 UTC - Autonomous ANR rollback triggered',
      '10:14:38 UTC - Sector 2/3 handover success rate restored to 99.8%',
    ],
  },
  {
    id: 'INC-2026-8501',
    title: 'Fiber Splicing Flap on Frankfurt Core Ring',
    timestamp: 'Yesterday',
    severity: 'INFO',
    status: 'Resolved',
    region: 'eu-central-1',
    towerId: 'TWR-EU-C1-01',
    towerName: 'EU-Central-1 gNodeB (Frankfurt)',
    metric: 'Availability (99.92%)',
    currentValue: '99.92%',
    baselineValue: '99.99%',
    rootCause: 'Scheduled maintenance fiber patch test performed by Dark Fiber provider.',
    impact: 'Zero user drop due to hitless MPLS fast-reroute.',
    recommendedActions: ['Audit completed', 'Post-maintenance OTDR test normal'],
    remediationExecuted: true,
  },
];
