import React, { useState } from 'react';
import { AIAnalysisResult, CellTowerNode } from '../types';
import { X, Copy, Check, Download, Printer, ShieldAlert, Sparkles, Server, Activity } from 'lucide-react';
import { StatusBadge } from './StatusBadge';

interface IncidentModalProps {
  isOpen: boolean;
  onClose: () => void;
  analysis?: AIAnalysisResult;
  towers?: CellTowerNode[];
}

export const IncidentModal: React.FC<IncidentModalProps> = ({
  isOpen,
  onClose,
  analysis,
  towers = [],
}) => {
  const [copied, setCopied] = useState(false);

  if (!isOpen || !analysis) return null;

  const incidentId = `INC-${new Date().getFullYear()}-${Math.floor(1000 + Math.random() * 9000)}`;
  const dateFormatted = new Date().toUTCString();

  const markdownReport = `
# NetSentinel AI - Autonomous NOC Incident Report
**Incident ID:** ${incidentId}  
**Date:** ${dateFormatted}  
**Classification:** ${analysis.severity}  
**Confidence:** ${analysis.confidenceScore}%  
**Source Engine:** ${analysis.sourceModel || 'Gemini 3.8 Flash Operations Copilot'}

---

## 1. Executive Summary
${analysis.incidentTitle}
${analysis.probableCause}

## 2. Telemetry Snapshot at Anomaly Crossing
- **Round-Trip Latency:** ${analysis.telemetrySnapshot.latency} ms
- **Packet Discard Rate:** ${analysis.telemetrySnapshot.packetLoss} %
- **Downlink Throughput:** ${analysis.telemetrySnapshot.throughput} Mbps
- **Network Jitter:** ${analysis.telemetrySnapshot.jitter} ms

## 3. Root Cause & Technical Details
${analysis.technicalDetails}

### Correlated Indicators:
${analysis.correlatedMetrics?.map((m) => `- ${m}`).join('\n') || '- None recorded'}

## 4. Business & Subscriber Impact
${analysis.impactAssessment}

## 5. Affected Infrastructure & Cell Nodes
${analysis.affectedNodes?.map((n) => `- ${n}`).join('\n') || '- None flagged'}

## 6. Actionable Engineering Remediations
${analysis.recommendedActions
  .map(
    (act, i) =>
      `${i + 1}. **${act.title}** (Risk: ${act.riskLevel}, Est. Recovery: ${act.estimatedRecoverySec}s)\n   ${act.description}`
  )
  .join('\n')}

---
*Generated by NetSentinel AI Autonomous Network Operations Center*
`.trim();

  const handleCopy = () => {
    navigator.clipboard.writeText(markdownReport);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([markdownReport], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${incidentId}-report.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-sm animate-in fade-in duration-200">
      <div className="relative w-full max-w-3xl max-h-[90vh] flex flex-col rounded-2xl border border-slate-800 bg-slate-900 shadow-2xl overflow-hidden">
        {/* Header */}
        <div className="flex items-center justify-between border-b border-slate-800 px-6 py-4 bg-slate-950/50">
          <div className="flex items-center gap-2.5">
            <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-purple-500/10 text-purple-400 border border-purple-500/20">
              <Sparkles className="h-4 w-4" />
            </div>
            <div>
              <h2 className="text-base font-bold text-white flex items-center gap-2">
                Incident Report Generator
                <span className="text-xs font-mono font-normal text-cyan-400">[{incidentId}]</span>
              </h2>
              <p className="text-xs text-slate-400">Audited autonomous telemetry diagnostic</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="rounded-lg p-1.5 text-slate-400 hover:bg-slate-800 hover:text-white transition-colors"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* Scrollable Report Body */}
        <div className="overflow-y-auto px-6 py-5 space-y-6 text-sm">
          {/* Top Metadata Cards */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
            <div className="rounded-lg border border-slate-800 bg-slate-950/40 p-3">
              <div className="text-xs text-slate-400">Severity</div>
              <div className="mt-1">
                <StatusBadge status={analysis.severity} size="sm" />
              </div>
            </div>
            <div className="rounded-lg border border-slate-800 bg-slate-950/40 p-3">
              <div className="text-xs text-slate-400">AI Confidence</div>
              <div className="text-sm font-bold text-cyan-400 mt-1">{analysis.confidenceScore}%</div>
            </div>
            <div className="rounded-lg border border-slate-800 bg-slate-950/40 p-3">
              <div className="text-xs text-slate-400">Observed Latency</div>
              <div className="text-sm font-bold text-white mt-1">{analysis.telemetrySnapshot.latency} ms</div>
            </div>
            <div className="rounded-lg border border-slate-800 bg-slate-950/40 p-3">
              <div className="text-xs text-slate-400">Packet Loss</div>
              <div className="text-sm font-bold text-rose-400 mt-1">{analysis.telemetrySnapshot.packetLoss}%</div>
            </div>
          </div>

          {/* Probable Cause & Synopsis */}
          <div className="rounded-xl border border-slate-800 bg-slate-950/60 p-4">
            <h3 className="text-xs font-semibold uppercase tracking-wider text-purple-400 mb-1 flex items-center gap-1.5">
              <ShieldAlert className="h-3.5 w-3.5" />
              Root-Cause Diagnosis
            </h3>
            <p className="text-sm font-semibold text-white mb-2">{analysis.incidentTitle}</p>
            <p className="text-xs leading-relaxed text-slate-300">{analysis.probableCause}</p>
            {analysis.technicalDetails && (
              <div className="mt-3 border-t border-slate-800/80 pt-2 text-xs text-slate-400 font-mono leading-relaxed bg-slate-950/50 p-2.5 rounded">
                {analysis.technicalDetails}
              </div>
            )}
          </div>

          {/* Impact Assessment */}
          <div className="rounded-xl border border-slate-800 bg-slate-950/60 p-4">
            <h3 className="text-xs font-semibold uppercase tracking-wider text-amber-400 mb-1 flex items-center gap-1.5">
              <Activity className="h-3.5 w-3.5" />
              Subscriber Impact Assessment
            </h3>
            <p className="text-xs text-slate-300 leading-relaxed">{analysis.impactAssessment}</p>
            {analysis.affectedNodes && analysis.affectedNodes.length > 0 && (
              <div className="mt-3 flex items-center gap-2 flex-wrap text-xs">
                <span className="text-slate-400">Flagged Infrastructure:</span>
                {analysis.affectedNodes.map((n, i) => (
                  <span key={i} className="px-2 py-0.5 rounded bg-slate-800 text-cyan-300 border border-slate-700">
                    {n}
                  </span>
                ))}
              </div>
            )}
          </div>

          {/* Remediations List */}
          <div className="rounded-xl border border-slate-800 bg-slate-950/60 p-4">
            <h3 className="text-xs font-semibold uppercase tracking-wider text-emerald-400 mb-2 flex items-center gap-1.5">
              <Server className="h-3.5 w-3.5" />
              Proposed Action Plan & Remediations
            </h3>
            <div className="space-y-2">
              {analysis.recommendedActions.map((act) => (
                <div key={act.id} className="rounded-lg border border-slate-800/80 bg-slate-900/60 p-3 text-xs">
                  <div className="flex items-center justify-between font-medium text-white mb-1">
                    <span>{act.title}</span>
                    <span className="text-[10px] px-2 py-0.5 rounded bg-slate-800 text-slate-300">
                      Est: {act.estimatedRecoverySec}s
                    </span>
                  </div>
                  <p className="text-slate-400">{act.description}</p>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Footer Actions */}
        <div className="flex flex-wrap items-center justify-between gap-3 border-t border-slate-800 px-6 py-3.5 bg-slate-950/60">
          <div className="text-xs text-slate-400">
            Model: <span className="text-slate-200">{analysis.sourceModel || 'Gemini 3.8 Flash'}</span>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className="flex items-center gap-1.5 rounded-lg border border-slate-700 bg-slate-800 px-3 py-1.5 text-xs font-medium text-slate-200 hover:bg-slate-700 transition-colors"
            >
              {copied ? <Check className="h-3.5 w-3.5 text-emerald-400" /> : <Copy className="h-3.5 w-3.5" />}
              <span>{copied ? 'Copied Markdown!' : 'Copy Markdown'}</span>
            </button>

            <button
              onClick={handleDownload}
              className="flex items-center gap-1.5 rounded-lg border border-slate-700 bg-slate-800 px-3 py-1.5 text-xs font-medium text-slate-200 hover:bg-slate-700 transition-colors"
            >
              <Download className="h-3.5 w-3.5" />
              <span>Download (.md)</span>
            </button>

            <button
              onClick={() => window.print()}
              className="flex items-center gap-1.5 rounded-lg bg-cyan-600 px-3.5 py-1.5 text-xs font-semibold text-white hover:bg-cyan-500 transition-colors"
            >
              <Printer className="h-3.5 w-3.5" />
              <span>Print Report</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
